language: objective-c

os: osx
osx_image: xcode8

env:
  matrix:
    - NAME='iPhone 6' OS=8.4
    - NAME='iPhone 6' OS=9.3
    - NAME='iPhone 6' OS=10.0

script:
    - xcodebuild test -project RMMultipleViewsController-Demo.xcodeproj -scheme RMMultipleViewsController-Demo -sdk iphonesimulator -destination "platform=iOS Simulator,name=$NAME,OS=$OS"

